version: '3.8'

volumes:
  pgdata:

networks:
  app-network:

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: securepass
      POSTGRES_DB: productdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "appuser"]
      interval: 10s
      retries: 5
    restart: unless-stopped

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    environment:
      SPRING_PROFILES_ACTIVE: default
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build: ./frontend
    depends_on:
      - backend
    networks:
      - app-network
    ports:
      - "8081:8080"
    restart: unless-stopped
