[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = ""
healthcheckPath = "/actuator/health/readiness"
healthcheckTimeout = 600
restartPolicyType = "NEVER"

[environment]
PORT = "8080"
