spring:
  datasource:
    url: jdbc:postgresql://db:5432/productdb
    username: appuser
    password: securepass
  jpa:
    # Force Hibernate as JPA provider
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      # Enable Hibernate-specific features
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        # Enable Hibernate-specific optimizations
        jdbc:
          batch_size: 20
          fetch_size: 50
        cache:
          use_second_level_cache: false
          use_query_cache: false
server:
  port: 8080

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    disable-swagger-default-url: false
  show-actuator: false
  packages-to-scan: com.example.backend
  paths-to-match: /api/**
  writer-with-order-by-keys: true
