spring:
  datasource:
    url: jdbc:postgresql://db:5432/productdb
    username: appuser
    password: securepass
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 8080
