spring:
  datasource:
    url: jdbc:postgresql://db:5432/productdb
    username: appuser
    password: securepass
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
